FROM golang:1.9-alpine
COPY templates/ /app/templates/
COPY resources/ /app/resources/
COPY resources/img /app/resources/img
COPY migrations/ /app/migrations/
COPY .env /app
ADD spacerace /app
WORKDIR /app
CMD ["/app/spacerace", "server"]
