version: '3'
services:

    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: spacerace
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - '/spacerace/pgdata:/var/lib/postgresql/data/pgdata'

    spacerace:
        image: rbaderts/spacerace
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            SPACERACE_DB_HOST: spacerace-db

            #    container_name: spacerace
        ports:
            - "8080:8080"

